version: 2

updates:
  - package-ecosystem: github-actions
    directory: /
    target-branch: main
    schedule:
      interval: daily
    open-pull-requests-limit: 5
    cooldown:
      default-days: 7
    groups:
      actions:
        patterns:
          - '*'

  - package-ecosystem: gomod
    directory: /
    target-branch: main
    schedule:
      interval: daily
    open-pull-requests-limit: 5
    cooldown:
      default-days: 7
    groups:
      actions:
        patterns:
          - '*'

  - package-ecosystem: nix
    directory: /
    target-branch: main
    schedule:
      interval: daily
    open-pull-requests-limit: 5
    cooldown:
      default-days: 7
    groups:
      actions:
        patterns:
          - '*'
